# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twilioflow}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dhananjay Keskar, Memamsa LLC"]
  s.date = %q{2010-07-03}
  s.description = %q{Twilioflow provides a Workflow model, Ruby specifiers for voice responses and RESTful controllers that act on Twilio request parameters to effect state transitions and automatically generate TwiML Response XML.}
  s.email = %q{dkeskar@memamsa.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/twilio/templates/config/twilio.yml",
     "generators/twilio/templates/controller.rb",
     "generators/twilio/templates/edit.html.erb",
     "generators/twilio/templates/lib/twiliolib.rb",
     "generators/twilio/templates/migration.rb",
     "generators/twilio/templates/model.rb",
     "generators/twilio/templates/twilio.twiml.builder",
     "generators/twilio/twilio_generator.rb",
     "init.rb",
     "lib/twilioflow.rb",
     "lib/workflow/ivr_workflow.rb",
     "lib/workflow/workflow.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/twilioflow_test.rb"
  ]
  s.homepage = %q{http://github.com/dkeskar/twilioflow}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails plugin for Twilio telephony apps}
  s.test_files = [
    "test/test_helper.rb",
     "test/twilioflow_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
